export const projectTags = [
  { title: "CSS", count: 27 },
  { title: "HTML", count: 23 },
  { title: "JavaScript", count: 16 },
  { title: "Python", count: 11 },
  { title: "React", count: 11 },
  { title: "Bootstrap", count: 8 },
  { title: "Firebase", count: 8 },
  { title: "Node", count: 7 },
  { title: "MongoDB", count: 7 },
  { title: "Tailwind", count: 6 },
  { title: "Flutter", count: 6 },
  { title: "Solidity", count: 4 },
  { title: "Express", count: 4 },
  { title: "Next", count: 4 },
  { title: "Dart", count: 4 },
  { title: "Kotlin", count: 3 },
  { title: "Git", count: 3 },
  { title: "MySQL", count: 3 },
  { title: "MERN", count: 3 },
  { title: "React.js", count: 3 },
  { title: "TailwindCSS", count: 3 },
  { title: "Typescript", count: 2 },
  { title: "NextJs", count: 2 },
  { title: "Ethereum", count: 2 },
  { title: "Blockchain", count: 2 },
  { title: "MongoDb", count: 2 },
  { title: "Nodejs", count: 2 },
  { title: "js", count: 2 },
  { title: "CSS3", count: 2 },
  { title: "Html", count: 2 },
  { title: "Shell", count: 2 },
  { title: "Figma", count: 2 },
  { title: "GitHub", count: 2 },
  { title: "three.js", count: 2 },
  { title: "Azure", count: 2 },
  { title: "mongodb", count: 2 },
  { title: "Tensorflow", count: 2 },
  { title: "PHP", count: 2 },
  { title: "React Js", count: 2 },
  { title: "bootstrap", count: 2 },
  { title: "HTML5", count: 2 },
  { title: "Auth0", count: 2 },
  { title: "typescript", count: 2 },
  { title: "Postman", count: 2 },
  { title: "Flask", count: 2 },
  { title: "Web3", count: 1 },
  { title: "Polygon", count: 1 },
  { title: "IPFS", count: 1 },
  { title: "ML", count: 1 },
  { title: "ANN", count: 1 },
  { title: "CNN", count: 1 },
  { title: "OpenCV", count: 1 },
  { title: "IoT", count: 1 },
  { title: "echo3d", count: 1 },
  { title: "ReactThreeFibre", count: 1 },
  { title: "MERN stack.", count: 1 },
  { title: "Css", count: 1 },
  { title: "reactjs", count: 1 },
  { title: "firebase", count: 1 },
  { title: "material-ui", count: 1 },
  { title: "React.js and Firebase", count: 1 },
  { title: "API's", count: 1 },
  { title: "Sass/SCSS", count: 1 },
  { title: "MERN with firebase as database", count: 1 },
  { title: "FastAPI", count: 1 },
  { title: "Machine Learning", count: 1 },
  { title: "JSON and ReactJS", count: 1 },
  { title: "Jupyter Notebook", count: 1 },
  { title: "", count: 1 },
  { title: "VS Code", count: 1 },
  { title: "NPM", count: 1 },
  { title: "tailwindCSS", count: 1 },
  { title: "express", count: 1 },
  { title: "Discord.js", count: 1 },
  { title: "Puppeteer", count: 1 },
  { title: "Axios", count: 1 },
  { title: "jsDom", count: 1 },
  { title: "MonogDB", count: 1 },
  { title: "Moongoose", count: 1 },
  { title: "Java", count: 1 },
  { title: "Spring", count: 1 },
  { title: "RxJava", count: 1 },
  { title: "Spring Lambda", count: 1 },
  { title: "Apache TVM Machine Learning Compiler", count: 1 },
  { title: "Sqlite3", count: 1 },
  { title: "Tkinter", count: 1 },
  { title: "GUI", count: 1 },
  { title: "Bash", count: 1 },
  { title: "express js", count: 1 },
  { title: "nodejs", count: 1 },
  { title: "Golang", count: 1 },
  { title: "Docker", count: 1 },
  { title: "Linux-SGX", count: 1 },
  { title: "OLAP Databases", count: 1 },
  { title: "SQL Databases", count: 1 },
  { title: "NumPy", count: 1 },
  { title: "Pandas", count: 1 },
  { title: "Scikit-Learn", count: 1 },
  { title: "OpenAI", count: 1 },
  { title: "SCSS/CSS", count: 1 },
  { title: "Keras", count: 1 },
  { title: "Scikit Learn", count: 1 },
  { title: "Pytorch", count: 1 },
  { title: "Langchain", count: 1 },
  { title: "Gradio", count: 1 },
  { title: "Streamlit", count: 1 },
  { title: "Taiwlind Css", count: 1 },
  { title: "WebSocket", count: 1 },
  { title: "jQuery", count: 1 },
  { title: "Laravel etc..", count: 1 },
  { title: "Android Studio", count: 1 },
  { title: "Room Database", count: 1 },
  { title: "XML", count: 1 },
  { title: "MONGO DB", count: 1 },
  { title: "Node js", count: 1 },
  { title: "(and various css frameworks like scss used)", count: 1 },
  { title: "Express.js", count: 1 },
  { title: "Mongodb", count: 1 },
  { title: "EJS", count: 1 },
  { title: "Sendgrid", count: 1 },
  { title: "JAVASCRIPT", count: 1 },
  { title: "ASTRO", count: 1 },
  { title: "TAILWINDCSS", count: 1 },
  { title: "Node JS", count: 1 },
  { title: "Chakra UI", count: 1 },
  { title: "Bootstrap5", count: 1 },
  { title: "StripeAPI", count: 1 },
  { title: "Node", count: 1 },
  { title: "YAML", count: 1 },
  { title: "CSS3 & Vanilla Javascript", count: 1 },
  { title: "MetaMask", count: 1 },
  { title: "ThirdWeb", count: 1 },
  { title: "TailWind CSS", count: 1 },
  { title: "python3", count: 1 },
  { title: "fastapi", count: 1 },
  { title: "React .", count: 1 },
  { title: "AZURE", count: 1 },
  { title: "UX/UI DESIGNING", count: 1 },
  { title: "NETLIFY", count: 1 },
  { title: "JSON", count: 1 },
  { title: "Framer-motion", count: 1 },
  { title: "Express JS Javascript HTML CSS OpenAI  Postman", count: 1 },
  { title: "CSS modules", count: 1 },
  { title: "Google Analytics", count: 1 },
  { title: "express.js", count: 1 },
  { title: "ethereum", count: 1 },
  { title: "ethers.js", count: 1 },
  { title: "and Firebase", count: 1 },
  { title: "Django", count: 1 },
  { title: "Android", count: 1 },
  { title: "TypeScript: 5.0.3", count: 1 },
  { title: "Next.js: 13.2.4", count: 1 },
  { title: "TailwindCSS: 3.3.1", count: 1 },
  { title: "Redux tool kit", count: 1 },
  { title: "OAuth", count: 1 },
  { title: "Etherium", count: 1 },
  { title: "AWS", count: 1 },
  { title: "Jest", count: 1 },
  { title: "Github Actions (CI/CD)", count: 1 },
  { title: "Go Lang", count: 1 },
  { title: "Vue.js", count: 1 },
  { title: "python", count: 1 },
  { title: "golang", count: 1 },
  { title: "Appwrite", count: 1 },
  { title: "Next.js and Tailwind", count: 1 },
  { title: "Metrial UI", count: 1 },
  { title: "tailwind css", count: 1 },
  { title: "postcss", count: 1 },
  { title: "GPT-3", count: 1 },
  { title: "Vercel", count: 1 },
  {
    title: "HTML CSS JAVASCRIPT REACTJS NODEJS MONGODB FIREBASE",
    count: 1,
  },
  { title: "CI/CD", count: 1 },
  { title: "Docker.", count: 1 },
  { title: "PostgressSQL", count: 1 },
  { title: "JQuery", count: 1 },
  { title: "MERN Tailwind Css Api", count: 1 },
  { title: "RUST", count: 1 },
];
